### ISSUE TITLE
Start the planning of CI for the CCv1 milestone

### ISSUE THREAD

**Issue by wainersm** [confidential-containers/community#1]
The [CCv1 proposal](https://docs.google.com/presentation/d/1RVVJjFLW7Or1WD1IKqvu9l9oggpNNV4pW8kkvMzDhY0/edit#slide=id.g107d4428bf5_0_275) aims to delivery a **CI/CD (...) With and without a TEE, add confidential container integration tests** (slide 5), and so two milestones are proposed:

 1. February 2022: **Initial CI/CD, all CC PRs go through CC specific integration tests**
 2. April 2022: **TEE (At least one) backed CI**

I'm opening this issue to allow the community to discuss on open and plan accordingly to delivery the above features on time.

The deadlines are tighten, hence, In my opinion we should start by closing the scope of work into something really minimal. The use story that comes to my mind is:

**As a CC developer, I want my pull requests on repository X and branch Y to be tested on the environment Z so that maintainers are assured that the changes I'm proposing won't break the simplest possible use case of CC**

Please, help to refine the use story above. Assuming it is more or less the direction we want to follow, here goes some additional questions that I have:

1. the CC project is mult-repository/components, so what repository and branch we want to test?
2. what tests should it run? Do they already exist?
3. what is the environment it should be tested? OS, Architecture and Hardware (assuming we can start with a single environment then later adding more)
4. what is the kata containers configuration? Hypervisor, Kernel, Guest OS and specific configurations (again assuming we can start with a single configuration)
5. do we need kubernetes? If yes, what version and what CRI (containerd or cri-o)

Cc @ariel-adam @c3d @fidencio @fitzthum @Jakob-Naucke @sameo @stevenhorsman 

(Cc'ing people that I think will help on this work or are simply interested. But please spread the words... as I'm sure I am missing many names here).

**Comment by stevenhorsman** [comment]
@wainersm - thanks for getting the conversation started. I'll add some of my thoughts to your questions, but the situation is evolving, so they might already be out of date.
> 1. the CC project is multi-repository/components, so what repository and branch we want to test?

At the moment we are using [kata-containers/kata-containers:CCv0](https://github.com/kata-containers/kata-containers/tree/CCv0) and [kata-containers/tests:CCv0](https://github.com/kata-containers/tests/tree/CCv0) for our limited [CCv0 CI tests](http://jenkins.katacontainers.io/view/CCv0/) in the kata pipeline. I imagine as we progress with CCv1 we will rename, or create a new `CC` branch, but we are also hoping to merge some of the confidential containers content into the `main` branch (probably limited to the agent changes initially and probably after image-rs has been integrated. There are a few other CC related repos such as https://github.com/confidential-containers/image-rs and https://github.com/confidential-containers/attestation-agent, but I'd guess we'll probably pull them in as dependencies.
Also worth noting is that we mirror the `CCv0` versions of the kata-containers and tests repos to https://github.com/confidential-containers/kata-containers-CCv0 and https://github.com/confidential-containers/tests-CCv0, so if we want a separate confidential-containers pipeline then I guess we'd use those (again maybe renamed).

> 2. what tests should it run? Do they already exist?

At the moment there aren't any new tests added to the CCv0 branches, we just run the existing kata tests for regression purposes. I'm sure we'd look to change this and there are a few demos around that might be a good started point for automation.

> 3. what is the environment it should be tested? OS, Architecture and Hardware (assuming we can start with a single environment then later adding more)

For CCv0's regression testing @fidencio and I chose to so a small subset of the existing kata OS and configurations tested in order to not over-burden the kata pipeline, but still provide fairly wide coverage so picked ubuntu with containerd and QEMU, fedora with cri-o and ubuntu with firecracker. I think it is ok for regression testing, but we'd need some switches/feature toggles on new tests as we don't fully support all these configurations (eg image offloaded onto the guest in cri-o). As we mature then we can spread our coverage wider.
In the absence of test TEE environments, I guess we should start with the non-TEE tests, that obviously don't provide the full 'confidential computing' security, but allows us to start testing the attestation agent, image pull on guest, agent api restrictions etc. As we get more hardware we can begin to extend these out to different platforms.

> 4. what is the kata containers configuration? Hypervisor, Kernel, Guest OS and specific configurations (again assuming we can start with a single configuration)

I covered this a bit in my previous thoughts, but starting with the basics of ubuntu, QEMU seems a good approach and built out from there.

> 5. do we need kubernetes? If yes, what version and what CRI (containerd or cri-o)

I think that Kubernetes is a key part of the confidential containers vision, so we should be testing that scenario. I think we should just follow the `main` Kata community with versions for now and pick up `1.22`.
cri-o and containerd is a bit more complicated. Due to some changes we required in the containerd-shim we have to use a custom fork https://github.com/confidential-containers/containerd/tree/ali-CCv0 of containerd. From what I've heard Samuel and others mention is doesn't seem likely that those changes will be merged into `main` and that the containerd community is working on their own solution to these problems, but that might take some months. In the short term I think we are stuck with that fork, which is a key obstacle to us getting any of the host side kata changes (eg runtime, shim) merged into `main`.
I think we want to support cri-o, but no steps have been taken yet and it probably makes sense to engage them once we know a bit more about containerd's plan.

This is by know means the full answers and I'm sure others have better suggestions, but I wanted to try and capture the situation we are in at the moment, in case some people following this are not aware.

**Comment by Jakob-Naucke** [comment]
Chiming in for s390x/Secure Execution CI: I can not yet confirm resources, but it should be possible, albeit firewalled. Is Open Connect for Jenkins possible as a requirement?

**Comment by peterzcst** [comment]
Yes, we are also looking into this to connect a TDX machine for kata integration test.

**Comment by wainersm** [comment]
@stevenhorsman @Jakob-Naucke @peterzcst Below is the plan that I'd like to show on the CC meeting tomorrow (or today, depending when you are reading this....). Sorry for the short notice.

=======
Context

Currently we got [CI pipelines](http://jenkins.katacontainers.io/view/CCv0/) to test pull requests addressed to our CC branch of the Kata Containers project, however those are tests that ensure we don't introduce regressions to the "normal" Kata containers. As part of CCv1 proposal, we are aiming to delivery a "CI/CD (...) With and without a TEE, add confidential container integration tests" (slide 5) so that we begin catching CC specific regressions. This work will be particularly valuable for checking the rebases that Steve Horsman (and others) frequently carry out on our CC branch in the Kata Containers.  

Deliverables

 * Specific integration tests without TEE
 * Specific integration tests with TEE
 * CI pipelines

Scope
 * The CI pipelines will run for pull requests (PR) opened to the [kata-containers](https://github.com/kata-containers/kata-containers) and [tests](https://github.com/kata-containers/tests). Other repositories like [image-rs](https://github.com/confidential-containers/image-rs) and [attestation-agent](https://github.com/confidential-containers/attestation-agent) are out of the scope.
 * Test with containerd CRI and shimv2 (?)
 * Test with Kubernetes + Containerd
 * CRI-O is out of scope
 * Use QEMU as Kata hypervisor. Other hypervisors are out of scope for now 

Assumptions
 * The Kata CI resources (Jenkins and VMs on Azure) can be used

Environments
 * Ubuntu 20.04 (x86_64) VM - non-TEE tests
 * Fedora 35 (x86_64) VM - non-TEE tests
 * TEE tests - to be defined

Milestones
 1. February 2022: **Initial CI - all CC PRs go through CC specific integration tests**
 2. April 2022: **TEE (At least one) backed CI**

Work items

 ** Feb **

 * PoC: running a specific integration test without TEE
   * Test image pull on guest
 * Identify and detail more non-TEE tests
   * attestation agent, agent api restrictions, ...
 * Identify hardware requirements for TEE tests
   * pay special attention to security concerns

** Mar **
 * Implement the remaining non-TEE tests
 * Create non-TEE CI pipelines
 * Onboard hardware for TEE tests
 * Identify and detail TEE tests (mid-Mar)
 
** Apr **
 * Implement TEE tests
 * Create TEE CI pipelines

**Comment by stevenhorsman** [comment]
Hi @wainersm - thanks for pulling this together. I think this looks like a great start. I slightly concerned that the attempt to merge the `CC` code into `main` might impact this, but I think this is good to aim for and maybe just flag that up as a risk?

**Comment by wainersm** [comment]
> Hi @wainersm - thanks for pulling this together. I think this looks like a great start. I slightly concerned that the attempt to merge the `CC` code into `main` might impact this, but I think this is good to aim for and maybe just flag that up as a risk?

Hi Steve, thanks for the review. Yes, you are right, I will list it as a risk. thanks!

**Comment by wainersm** [comment]
@stevenhorsman done, added two risks to the plan.

**Comment by peterzcst** [comment]
@wainersm Could you pls add Peter(@peterzcst )/Arron(@arronwy ) as owner for Intel TDX TEE parts of CC CI?  Thx

**Comment by wainersm** [comment]
> @wainersm Could you pls add Peter(@peterzcst )/Arron(@arronwy ) as owner for Intel TDX TEE parts of CC CI? Thx

Done.

**Comment by wainersm** [comment]
> Thanks @wainersm . It looks a good start. I just have one question, why should we have to have Kata CI resources on Azure

Hi @peterzcst , thanks for the feedback. In my mind we should start small, that means running the tests which aren't dependent on hardware. For example, check the agent can pull the image inside the guest. Because adding hardware to the pool will be tricky, we could start running those kinds of tests on VM on Azure.

Am I missing something?

**Comment by hbrueckner** [comment]
> Chiming in for s390x/Secure Execution CI: I can not yet confirm resources, but it should be possible, albeit firewalled. Is Open Connect for Jenkins possible as a requirement?

As @Jakob-Naucke mentioned, I work on getting some IBM Z hw resource to perform CI with Secure Execution.

@wainersm Feel free to add me as HW owner for IBM Z / Secure Execution (SE)

**Comment by wainersm** [comment]
> > Chiming in for s390x/Secure Execution CI: I can not yet confirm resources, but it should be possible, albeit firewalled. Is Open Connect for Jenkins possible as a requirement?
> 
> As @Jakob-Naucke mentioned, I work on getting some IBM Z hw resource to perform CI with Secure Execution.
> 
> @wainersm Feel free to add me as HW owner for IBM Z / Secure Execution (SE)

Hi @hbrueckner , done. thanks!

**Comment by wainersm** [comment]
I will close this issue in favor of https://github.com/confidential-containers/community/issues/2 that contain the "final" plan and links to tasks.
