### ISSUE TITLE
Unique Version Numbering

### ISSUE THREAD

**Issue by dcmiddle** [confidential-containers/community#30]
From the Change Control section of https://bestpractices.coreinfrastructure.org/en/projects/5719/
 
The project results MUST have a unique version identifier for each release intended to be used by users. 

It is SUGGESTED that the [Semantic Versioning (SemVer)](https://semver.org/) or [Calendar Versioning (CalVer)](https://calver.org/) version numbering format be used for releases. It is SUGGESTED that those who use CalVer include a micro level value. 

It is SUGGESTED that projects identify each release within their version control system. For example, it is SUGGESTED that those using git identify each release using git tags.

**Comment by fitzthum** [comment]
I think that figuring out versioning is one of the most important organizational tasks for this project. Although most of our components already have some kind of versioning (thanks to Cargo.toml), we need a way to create versioned releases that encompass many different components. I think that the work we are doing with CICD and kata deploy is connected to this.

From a technical standpoint it seems like maybe Kata's `versions.yaml` file is the crux (although maybe it shouldn't all be based around Kata?). We also need to figure out how/when we want to make our releases. 

Any thoughts? Has this been discussed anywhere else yet? @fidencio @wainersm @sameo @stevenhorsman

**Comment by jodh-intel** [comment]
@fitzthum - I vote semver. It's proven, and is the *de facto* versioning scheme used by rust and golang [1]. However, I'm unclear about your comments around Kata's [versions database](https://github.com/kata-containers/kata-containers/blob/main/versions.yaml)? We use this to track external (non-rust, non-golang) dependencies, and that file is of course tracked under git so is effectively versioned to the Kata release version (which uses semver).

---

[1] - Well, strictly golang packages don't use semver as they use a leading `v` but if that's removed, it's semver ;)

**Comment by fitzthum** [comment]
@jodh-intel well what I was trying to get at is that we will need a place to map Confidential Containers version to the version of each subproject. The `versions.yaml` file more or less does this for Kata, but I'm not sure if the scope is right for CC. In the CCv0 branch `versions.yaml` tracks the version of the attestation agent, which is what we want, but there are other components, like the KBS that are out of the scope of Kata. Or if we're talking about enclave-cc, kata might not be in the picture at all.

**Comment by fitzthum** [comment]
> All in all, my most sincere suggestion is to version the "Confidential Containers" and the "Operator" with the very same versioning scheme, being bumped together, "released" together, as this is the "consumable solution". Everything else should have its own pace, its own cadence, its own versioning number, and we keep those into some sort of versions.yaml file, testing those, and strongly recommending people to use what we have tested.

I agree that we always want the operator to be in sync with the Confidential Containers release. The same is probably true for our hypothetical CC testing setup. We could even go as far putting the Confidential Containers versioning matrix in the operator repo and saying that a release of Confidential Containers is really a release of the operator. This might make it a bit tricky to update the operator on its own, though.

**Comment by fidencio** [comment]
> This might make it a bit tricky to update the operator on its own, though.

What are the cases that you see the operator being updated, **and released**, on its own (not involving a new "Confidential Containers" release)?  I cannot think about an example by myself.

**Comment by fitzthum** [comment]
> What are the cases that you see the operator being updated, and released, on its own (not involving a new "Confidential Containers" release)? I cannot think about an example by myself.

I think there are some cases where we might want to release just the operator. For instance if we find a bug in the operator that we want to fix immediately without changing any of the other components. I guess it would be reasonable to do a minor release in this case. It just might be a bit odd if we end up adding new stuff to the operator much faster than the other components, but that probably won't be the case.

**Comment by stevenhorsman** [comment]
> All in all, my most sincere suggestion is to version the "Confidential Containers" and the "Operator" with the very same versioning scheme, being bumped together, "released" together, as this is the "consumable solution". Everything else should have its own pace, its own cadence, its own versioning number, and we keep those into some sort of `versions.yaml` file, testing those, and strongly recommending people to use what we have tested.

I like this suggestion. As you rightly point out there is a limit to how much we could control the versioning and including of certain downstream components, such as those bundles in Kata, but as long as we maintain a good relationship with those components hopefully there won't be a situation where we are desperate for a fix in something like `image-rs` and Kata isn't, so we have to wait for their release.

I guess the big elephant in the room on this topic is testing and CI resources. At the moment we are just hopping on the Kata CI-CD pipeline, but there is a limit to what we can and should test in there and before we consider doing a 1.x release I think we are going to need a (CNCF hosted?) confidential-containers pipeline and workflow to provide testing based on the 'co-co' `versions.yaml` and probably to bundle the release components too.

**Comment by fidencio** [comment]
> I think there are some cases where we might want to release just the operator. For instance if we find a bug in the operator that we want to fix immediately without changing any of the other components. I guess it would be reasonable to do a minor release in this case. It just might be a bit odd if we end up adding new stuff to the operator much faster than the other components, but that probably won't be the case.

That's one case that I sincerely think we should bump the whole version of the project.
IMHO, we'd say ... "Confidential Containers x.y.z had an issue with the operator, x.y.(z+1) has it fixed".

**Comment by wainersm** [comment]
I've re-write this comment many times because there are a lot of uncertainties and possibilities. Here goes my opinion. 

In https://github.com/confidential-containers/community/issues/30#issuecomment-1119021629 @fidencio draw the scenario perfectly, he mentioned the fact that Confidential Containers is an umbrella project (which I agree) and its individual components should have their own pace and release cadence. Confidential Containers would be kind of a downstream "aggregator" component (herein "Co-Co"). That seems reasonable to me. Then I would like to evolve the discussion to:

  a) Will Co-Co be released in a fixed cadence? (e.g. bi-monthly, quarterly...)
  b) If the sub-components have their own release cadence, that misalignment to Co-Co release may be cumbersome. E.g. we may need to patch a given component because it will be released with a needed fix just after Co-Co's. So Co-Co will behave like a distro build.
  b) Back to the original question of this issue: SemVer or CalVer versioning schema? I tend to think that semVer is not so meaningful ("is 3.0 any better than 2.4?") and comes with complications like "What should drive the bump of the Major version?"

**Comment by bpradipt** [comment]
> All in all, my most sincere suggestion is to version the "Confidential Containers" and the "Operator" with the very same versioning scheme, being bumped together, "released" together, as this is the "consumable solution". Everything else should have its own pace, its own cadence, its own versioning number, and we keep those into some sort of `versions.yaml` file, testing those, and strongly recommending people to use what we have tested.

This is a good suggestion. We can keep the dependency matrix in the `versions.yaml` and also add it to the release notes.

**Comment by fidencio** [comment]
> a) Will Co-Co be released in a fixed cadence? (e.g. bi-monthly, quarterly...)

This is a really good question, and I don't think anyone has actually thought about it yet, mainly with the consequences of this decision.
 
Right now I think is **way too early** to discuss the cadence, but it may be a good time to understand the consequences of the chosen cadence.

Kata Containers, for instance, has one new release every 4 months, and it maintains only one stable branch (which is maintained for 4 months, till the next minor release).  Depending on the cadence chosen for CoCo, CoCo may be using a non-maintained version of Kata Containers.  /o\ .

Someone will have to understand the release cadence of each and every single component that's consumed by CoCo, and then make the decision of aligning the release with the major components, or patch some of those under this "umbrella" (and, trust me, that's not a pleasant path to take).

> b) If the sub-components have their own release cadence, that misalignment to Co-Co release may be cumbersome. E.g. we may need to patch a given component because it will be released with a needed fix just after Co-Co's. So Co-Co will behave like a distro build.

I'd say it depends a lot.  If the component is **only** used by CC, well, we bump the version and use the new version.  We have been bumping things like Cloud Hypervisor on Kata Containers stable branches without any issue, so we could bump td-shim, ocicrypt-rs, image-rs, attestation-agent, as long as it's bringing in a **bug fix**.

If a new feature is required though, this shows 3 things: bad planning, bad syncing, and also probably bad execution; and this is something that can be easily avoided by giving voice to the people familiar with / working on the projects being used to decide what makes or what doesn't make sense to get in.

**Comment by bpradipt** [comment]
> Kata Containers CI / CD pipeline will still be around, as several things will happen on the Kata Containers domain. But in order to have an official release I'd expect that some sort of CI would happen also on each and every single component we host; and also in the integration we provide, as in, integration and functional tests on the Operator side.
> 
> This is a huge task, maybe the hardest one. I'm just super glad we have folks with enough experience on doing that around, willing to help with this one.

This is indeed a big one. And we are yet to get started with functional and integration tests on the Operator side.

**Comment by c3d** [comment]
To complement what has been already written here, a point I made during the meeting is that with semver, there is a relatively common convention that a a version 0.x.y is unstable, pre-release, and makes no guarantee. I believe that we need to stick to that while we are in the process of implementing things, until we have a good feeling that the core value add, _confidentiality_, can be delivered reliably.

This does not necessarily apply to components. A component may be closer to completion than the whole. For example, we could have a KBS 1.x at some point for CC 0.1, then decide in version 0.2 that we need to switch to an entirely different protocol in KBS 2.x. The 1.x -> 2.x switch would mark the compatibility breakage related to the component. The 0.1 to 0.2 switch would be allowed to break anything anyway.

**Comment by fitzthum** [comment]
There was an unofficial/informal discussion about versioning with some of the TSC members. Here is a summary: 

First, it seems like there is some convergence around having a `versions.yaml` file that keeps track of which version of every subproject has been tested and is supported. This will allow us to continue developing subprojects independently but also keep track of which components have been tested together. There are still a few things to figure out here (like the best way to synchronize releases of subprojects and the main project), but I think that we are generally on the same page. 

Where should this `versions.yaml` file live? One option is to put it in the operator repository. This would cement the operator as the way that the project is surfaced, which I think is a good idea. There have been some concerns that if we release CC too early, we might ship something that is hard to use or even broken. This could deter people from trying future releases. By positioning the operator as the focal point of the release, we can make sure that we always release something that is coherent and easy to use. We can also use the operator as a gatekeeper for experimental features. This way the community can keep working on advanced features, but we don't have to expose them to users. This can help us reconcile our goal of adding more features and our goal of providing a simple, stable release that is easy to consume.

So what do we need to do before we can make a first release? Well, we need to add the versioning stuff to the operator and we need some kind of CI that will guarantee that the operator is always functional and coherent. As soon as we have this, I think we might as well make release `0.0.1`. It's probably a good idea to start releasing things soon so that we can get some practice making releases before we arrive at `0.1.0`. I think we already have enough basic features to release something as long as we can get the operator and CI sorted out. That said, we probably won't publicize our early releases very widely, because we still have a lot of features that need to be added. 

Once we have started making point releases, we will need to decide when to release version `0.1.0` and eventually version `1.0.0`. This can be discussed separately.

Does this seem like it could be a reasonable plan?

@dcmiddle @magowan @sameo @ariel-adam @bpradipt @peterzcst @jiangliu

**Comment by c3d** [comment]
> Does this seem like it could be a reasonable plan?

To me, yes.

**Comment by sameo** [comment]
FWIW agreement was reached for the first release to be tagged as `0.1.0`.

**Comment by ariel-adam** [comment]
We agree on the following: 

[Semver](https://semver.org/) - 0.1.0  will be our first release and we move on to 0.2.0 (third digit is for patches/crises)

**Comment by ariel-adam** [comment]
@dcmiddle is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by dcmiddle** [comment]
verified all repos in v0.1 release were tagged accordingly.
