### ISSUE TITLE
[CNCF] Governance

### ISSUE THREAD

**Issue by sameo** [confidential-containers/community#9]
### Parts of the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) tracked by this issue

All governance related parts.

*This is the list of all bullet points from the [CNCF onboarding issue](https://github.com/cncf/toc/issues/799) that this issue will track:*

* [x] *Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/*
* [x] *Create maintainer list + add to aggregated https://maintainers.cncf.io/ list by submitting a PR to it*
* [x] *Provide emails for the maintainers added to https://maintainers.cncf.io/ in order to get access to the maintainers mailing list and ServiceDesk*

**Comment by fitzthum** [comment]
First off, I recommend reading the [CNCF pages about governance](https://contribute.cncf.io/maintainers/governance/). They are nicely put together. The CNCF does not mandate that member projects use any particular governance structure, but rather that they adopt something that is transparent and well documented. They provide a number of examples. 

In the past we briefly talked about creating an architecture committee with members chosen by each company participating in the project. There are existing CNCF projects that use a similar policy. I think the goal was to minimize community overhead in choosing AC members and to make sure that each project stakeholder is represented. This had been discussed as a temporary measure prior to potential CNCF admission, but we never got beyond discussing it. We could potentially continue with this approach.

I think there are potentially two issues with this approach that we should talk about. First, it's not clear what the AC would actually do. I guess the idea is that if we run into any contentious issues in the community, the AC could weigh in after they have been discussed with the larger group. It's not clear what other roles the committee might take on. Second, we were slightly vague with how many people would join from each company. We didn't want to set a hard limit at one because there are several large companies participating where members come from disjoint areas of the company and are focusing on totally different areas of the project. On the other hand, if more than one member is allowed, companies might feel like they need to send more people to increase their influence. This potential AC does not address running the weekly meetings, which is currently one of our main administrative tasks and should be documented.

Note that the CNCF issue does not list figuring out a definitive solution for governance. In the their guidance they stress the need to document what is actually happening with governance rather than what we hope will happen. Maybe we can check off these issues without having entirely settled on a process. That said, one of the work items is to provide a list of maintainers. Most CNCF projects have one main repo, so the list of project maintainers is simply the maintainers of the repo. For us things aren't so simple. We could provide a maintainers file that is a union (or an intersection) of the maintainers files for each repo, or it's possible that an architecture committee could serve as the project maintainers.

**Comment by magowan** [comment]
I would go with just the union of maintainers - it reflects our current governance :-) and less conversation needed?

I do agree with the question  "What do we think an AC will do?"
As mentioned there is some effort happening to shape the agenda for Thursday but all decisions essentially get made on Thursday and everyone is free to offer up a topic for Thursday meetings.

I guess the openness of the AC (once we decide what it does :-) ) is a question. 
is it open to all who are interested but actions typically default onto the AC members?
In which case does being AC member get you influence? or responsibility? :-)

And whatever our focus for the AC, I think the onboarding process and process to reach incubating clearly shows there is much more than in depth knowledge of the code needed. We need to be conscious of balancing the skills, viewpoints, experiences we can call on , not just for AC but for all our meetings.

**Comment by fitzthum** [comment]
Ok, a few thoughts to refine the initial AC idea. 

First, I think we would probably want a different name. Architecture Committee implies a fairly specific role. I think we want something a bit more general that can serve a handful of purposes, including setting the agenda for the community meetings, resolving any otherwise inconclusive community debates, and anything else that will help facilitate development. 

Since these tasks vary widely, I think we should break them into two categories; tasks that require quorum and tasks that don't. Since our community is spread out across many different time zones, weekly meetings with the entire committee might be challenging. Most tasks don't really require everyone to be present, however. Perhaps we can set out basic operations, such as planning the weekly meetings, that do not require quorum and can easily happen every week. Most of the committee would only need to be present when there are more complex or significant decisions to make, such as creating new repos or weighing in on a community debate. The committee can also also appoint people to facilitate the weekly meeting. 

When it comes to membership, I think it's fine to say that we will have up to two members from each company. The question is what companies are represented? Maybe it makes sense to have some kind of participation requirement i.e. every company that has at least N contributions gets seats on the committee? 

Given that there has so far been little interest in hashing out governance, I think we are almost certainly not going to have anything formalized as part of the onboarding process. This is fine. We just need to be moving towards open governance. That said, we do need a list of maintainers for the onboarding process. I don't think this refers to everyone who can merge PRs so much as to the sort of people that would be on a hypothetical committee. If we don't have governance figured out, we may need to come up with this somewhat arbitrarily.

**Comment by sameo** [comment]
> First, I think we would probably want a different name. Architecture Committee implies a fairly specific role. I think we want something a bit more general that can serve a handful of purposes, including setting the agenda for the community meetings, resolving any otherwise inconclusive community debates, and anything else that will help facilitate development.
> 

For naming, we could go with something like a *(Technical) Steering Committee*.
Although naming is important, I think the scope and responsibilities of this body is what matters the most. The SC would be representing the CC project as a whole. Its scope would be mostly about managing the project, defining its long term strategy and roadmap and driving the community around it. SC duties would not be about maintaining any specific CC project or making day-to-day, project specific technical decisions. Those should be left to the projects maintainers teams, defined for each project.

To formalize it slightly more: 

### Steering Committee Scope

* Project high level strategy (Technical and non technical) definition and drive
* Project administration: Weekly meetings, github organization maintenance, etc.
* Project external representation
* Community management and guidance, including e.g. community debate arbitration.

### Steering Committee **Non** Scope

* Project maintainer-ship. Each CC repo should be maintained by its own set of maintainers, which are defined separately.
* Project specific technical decisions, unless the project maintainers ask for the SC to chime in and provide input.

> Since these tasks vary widely, I think we should break them into two categories; tasks that require quorum and tasks that don't. Since our community is spread out across many different time zones, weekly meetings with the entire committee might be challenging. Most tasks don't really require everyone to be present, however. Perhaps we can set out basic operations, such as planning the weekly meetings, that do not require quorum and can easily happen every week. Most of the committee would only need to be present when there are more complex or significant decisions to make, such as creating new repos or weighing in on a community debate. The committee can also also appoint people to facilitate the weekly meeting.
> 
> When it comes to membership, I think it's fine to say that we will have up to two members from each company. The question is what companies are represented? Maybe it makes sense to have some kind of participation requirement i.e. every company that has at least N contributions gets seats on the committee?
>

To be pragmatic, I think the following companies probably cover more than 95% of the project contributions so far:

- Alibaba
- AMD
- Apple
- IBM
- Intel
- Red Hat

Having each of those companies appoint 1 or 2 individuals to the SC would make it for a reasonably sized **initial** committee. The only requirement could be for each SC member to be a project contributor, i.e. having contributed at least once to any CC project over the past 12 months.
But here again the most important part is to define how one can get into the SC. The **initial** definition of the committee will always be arbitrary and kind of self-defined. What we must define is how and when the committee seats are renewed, and make sure this is an open process. So the first committee definition is arbitrary, sure. But it's mostly for bootstrapping reasons, and it comes with a clear rules for renewing itself in an open and inclusive way.

If the above makes sense, I can start discussing with all those companies and make a proposal for an initial SC (Or whatever we want to call it) members list.

**Comment by ariel-adam** [comment]
I think that is a good way for us to start moving froward with the COCO project at least for 6 month until we can deliver proper releases.
A trigger to change the SC in my opinion should be new companies joining the project with actual contributions and ensuring they are also represented in the SC.

**Comment by fidencio** [comment]
> But here again the most important part is to define how one can get into the SC.

About this, I'd like to raise a few points here.

We do want to have this process as transparent as possible, and we should have it in a way it's not disruptive for the project, meaning that I'd avoid changing way too many people at once.

With Samuel's proposal, we'd have a quite large Steering Committee, I can think about 9 to 11 people there, and considering the scenario with the maximum possible change, we'd have 9 to 11 new people steering the project after an election, and that may have some not so good side effects.

What I'd like to suggest with this in mind is that we go ahead and have this first round, as suggested by Samuel, with 9 to 11 people in.  But  we also agree that elections should happen twice per year, with ~6  and ~5 members on each one of the elections, preferrably not having 2 seats of the same company being renewed at the same time.  I know, details, sorry about those, but I think those are important at this point.

So, a quick recap (take the numbers as an example, not as the formal proposal):
* Steering commit with 11 people.
* Announce the first election to happen in 12 months, and declare which are the seats that will be available for the first election.
* Announce the second election to happen in 18 months, and declare which are the seats that will be available for the second ection.
* Let the companies with 2 seats decide who should be up for the first and for the second election.
* Make it clear that after the first and second round of elections, elections for those seats will happen every year, with ~6 months interval between themselves.

This would ensure a nice transition for those coming to the Steering Committee, and ensure we never ever get to the following situations:
* Have the whole committee being replaced at once (unlikely, I know, but still better to have it covered).
* A company doesn't disappear entirely from the A/C, unless they decide to explicitly step down.

Do these points make sense to folks involved in the discussions?

**Comment by fitzthum** [comment]
@fidencio @sameo There are a lot of different ways to do open governance. If we are worried about churn, we can adjust the timing of elections. We aren't even required to have elections, although it might be a good idea (or maybe an empty formality?). 

I am a bit uncertain about combining the representation of each company with elections. Is the idea that each company having seats is an invariant or just a starting point? Maintaining some corporate distribution is somewhat at odds with having community-wide elections (even if only one seat goes up for election at a time). Which one is more important?

**Comment by sameo** [comment]
> @fidencio @sameo There are a lot of different ways to do open governance. If we are worried about churn, we can adjust the timing of elections. We aren't even required to have elections, although it might be a good idea (or maybe an empty formality?).
> 

Not all open source project use elections for appointing their TSC/SC/Board/TOC members, and that may be fine as well. Other solutions like SC members appointing new ones feel less open and less inclusive to me.

> I am a bit uncertain about combining the representation of each company with elections. Is the idea that each company having seats is an invariant or just a starting point?

IMHO it should just be a starting point. After that, whatever process we want to follow to renew the SC should have very simple rules, not any kind of pay-for-play stuff. The simplest I can think about is that anyone who contributes to the project can apply for an SC seat. Or we can restrict it a little further by saying that an SC member has to be a maintainer of one of the projects. Voters should be contributors though.
To me the most important aspect is that this is a community driven decision, and if the community wants to see a balanced corporate distribution it can decide to do so. Or not.  

> Maintaining some corporate distribution is somewhat at odds with having community-wide elections (even if only one seat goes up for election at a time). Which one is more important?

As I said, to me the most important is the the community is given a fair way to decide. Elections is one tool for that, there might be others/

**Comment by dcmiddle** [comment]
Here's a talk on Minimum Viable Governance: https://www.youtube.com/watch?v=C2-_MjzP-Rs 
Most relevant sections are from minutes 3 to 29 and 43 to 46 (CNCF).
  
Highlights for me are that: It shouldn’t be focused on voting. Creating culture is more important than creating rules.

Values to facilitate decision making e.g.:

- Community > Company
- Distribution > Centralization
- Improvement > Stagnation
- Automation > Process

Governance design process:

- Write down what you are doing now
- Know you won’t get it right at first
- Discuss empathize iterate.

**Comment by sameo** [comment]
Another interesting link, from github (The organization): https://github.com/github/MVG

**Comment by fitzthum** [comment]
The MVG has the TSC itself appoint new members. I think this sort of thing is very common, but to me it seems only a few steps beyond a benevolent dictator; old school and not very community-driven. Elections can seem like the most open way to run a community, but I think there are also some issues there. 

More than anything open governance is supposed to be clear. While the process for elections might be clear on one level, elections can also introduce a lot of unspoken dynamics. For example, some communities have regular elections but the candidates are always unopposed. Is it just a coincidence that there are always the same number of candidates as seats? More likely there are subtle community dynamics, assumptions about who is qualified to be on the committee, or unwritten rules of balance or legacy. This is probably more related to apathy than anything sinister, but nonetheless there are ways in which elections aren't very clear to an outsider. And imagine that an election is contested, does the average community member actually have a reason to pick one candidate over another?

One thing that I think is very important to this community is our collaboration across different companies, countries, and cultures. The project simply wouldn't be what it is if we hadn't figured out a relatively effective way to do this. I think whatever governance we end up with should represent our diverse stakeholders and I worry somewhat that elections might favor people who have more experience with certain types of open source communities, or who live in nearby timezones, or who are more comfortable speaking English. Maybe I am overthinking things.

**Comment by fidencio** [comment]
Every process can have its flaws, but I still think elections are one of the most open and reasonable ways to do so.  And it still has basic problems to be solved varying from who should have rights for voting, or even how to avoid fraud in the process.

Anyways, I guess that whatever we end up choosing we're on the same page about having the process open, well documented, and covering cases for people to step up and step down to those positions.

Another interesting link: https://developer.ibm.com/articles/open-governance-community/

**Comment by sameo** [comment]
Trying to summarize the conversation, I feel there are a few key points that we agree upon:

1. We need to build a Steering Committee (SC) for the project, and its scope should be mainly about:
   * Defining the project high level strategy and roadmap
   * Administrating the project (repos, teams, etc)
   * Building and growing the Confidential Containers community
3. The SC should initially be made of 1 or 2 representatives from each company that is currently contributing to the project.
4. The process for adding/replacing members of the SC should be open, clear and simple. This could be either done through periodic elections or by having SC members nominate and decide who can join the SC. In both cases, this should be done in the open and discussions should be public. 

Assuming there's a consensus on the 3 above points, and after discussing with, I hope, all relevant stakeholders, I'm proposing the following:

1. The initial SC members would be:
    * Larry Dewey (@larrydewey) from AMD
    * Jiang Liu (@jiangliu) and Jia Zhang (@jiazhang0) from Alibaba
    * James Magowan (@magowan)  and Tobin Feldman-Fitzhum (@fitzthum) from IBM
    * Peter Zhu (@peterzcst) and Dan Middleton (@dcmiddle) from Intel
    * Pradipta Banerjee @bpradipt  and Ariel Adam (@ariel-adam) from Red Hat
    * Samuel Ortiz (@sameo)
2. One of the first assignment for the SC would be to define an agreeable process for renewing its members. We'd let them choose between elections or nominations, or some other process they'd see fit. Again, the key point here is for this process to be open and transparent.

I could start formalizing this a little bit more if there is no strong disagreement.

And again, the CNCF on-boarding process does not depend on us having completely define our governance model, but by working and building on it. As @dcmiddle highlighted, this is going to be an iterative process, and I hope that this proposal leaves room for improvement once the initial SC is created.

**Comment by sameo** [comment]
See PR #34

**Comment by larrydewey** [comment]
I agree with everything that has been discussed so far. I like the idea of keeping things open, and I like the idea of holding votes at a regular cadence. The one question I have is regarding the membership / entry into the proposed SC: As the project become more popular, will the requirements for consideration for entry into the SC also scale upward? I am curious about this, as depending on activity, this could be monopolizing in either direction, as code or documentation specific contributions by count could potentially leave out weights of importance or quality. I will reference this in #34 , as well, as perhaps that is a better place to ask these questions?
